[backend]
precision = double
rank-allocator = linear

[backend-cuda]
device-id = local-rank

[constants]
; pyfr constants
gamma = 1.4
Re = 2.3e6
Pr = 0.71
mu = 4.34782609e-7 # 1 / Re = 4.34782609e-7
cpTref = 0.1
cpTs = 0.169846
rho_inf = 1.0
u_inf = 1.0
v_inf = 0.0
w_inf = 0.0
p_inf = 0.02857142857 # 1 / (gamma * M^2)

[solver]
system = navier-stokes
order = 3
shock-capturing = entropy-filter
viscosity-correction = sutherland

[solver-time-integrator]
formulation = std
scheme = rk4
tstart = 0.0
tend = 5.0
dt = 1.5e-5
controller = none

[solver-entropy-filter]
d-min = 1e-5
p-min = 1e-5
e-tol = 1e-7
niters = 8
formulation = nonlinear

[soln-filter]
nsteps = 10
alpha = 36.0
order = 3
cutoff = 1

[solver-interfaces]
riemann-solver = rusanov
ldg-beta = 0.5
ldg-tau = 0.1

[solver-interfaces-quad]
flux-pts = gauss-legendre

[solver-elements-hex]
soln-pts = gauss-legendre

[soln-bcs-farfield]
type = sup-in-fa
rho = rho_inf
u = u_inf
v = v_inf
w = w_inf
p = p_inf

[soln-bcs-wall]
type = no-slp-adia-wall

[soln-bcs-outflow]
type = sup-out-fn

[soln-bcs-symplane]
type = slp-adia-wall

[soln-ics]
rho = rho_inf
u = u_inf
v = v_inf
w = w_inf
p = p_inf

[soln-plugin-nancheck]
nsteps = 1000

[soln-plugin-writer]
dt-out = 1.0
basedir = out
basename = sol-{t:.2f}

[soln-plugin-integrate]
nsteps = 1000
file = massflow.csv
file-header = true
int = rho*u
region = box((1.04, 0.13, -0.01), (1.06, 0.25, 0.11))